### ISSUE TITLE
donation button broken

### ISSUE THREAD

**Issue by NoahZinsmeister** [kremalicious/blog#210]
cool site! happy to see you're using web3-react.

i was playing around with the donation page and i was getting errors trying to send a tx, specifically `Uncaught (in promise) Error: overflow (fault="overflow", operation="BigNumber.from", value=2000000000000000000, version=bignumber/5.0.0-beta.135)`

**Comment by kremalicious** [comment]
hey there, thanks for dropping by! Indeed there was a bug caused by a combination of passing a number, and by rolling my own conversion. Fixed by just utilizing `parseEther` from ethers.js

And thank you very much for this excellent project, so far it's a joy to use

**Comment by kremalicious** [comment]
haha, thanks for the huge cappuccino!
